### ISSUE TITLE
2.1 - Prototype pour tester le contrôle de son à l'aide de Max et Arduino 

### ISSUE THREAD

**Issue by CorKarine** [task-tim/Chere-Sasha#9]
- [x] **2.1 - 1** Faire le code Arduino
- [x] **2.1 - 2** Faire le code Max
- [x] **2.1 - 3** Connecter les 2 ensemble pour voir si le tout marche ensemble
SUCCÈS

**Comment by angelinajeca** [comment]
- [ ] 2.1 - 1 Faire le code Arduino
- [ ] 2.1 - 2 Faire le code Max
- [ ] 2.1 - 3 Connecter les 2 ensemble pour voir si le tout marche ensemble

**Comment by angelinajeca** [comment]
J'ai créer le code Max pour que l'on puisse activer et désactiver une musique a l'aide d'une photorésistance. J'ai aussi créer le code Arduino pour pouvoir connecter le patch Max a l'arduino (physique).
